{
 "title": "Servers",
 "description": "Windows host dashboard for Servers",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"win_system\" WITH KEY = \"host\""
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": "SHOW TAG VALUES FROM \"win_disk\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "process",
    "label": "Process",
    "query": "SHOW TAG VALUES FROM \"win_proc\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   },
   {
    "name": "network",
    "label": "Network Interface",
    "query": "SHOW TAG VALUES FROM \"win_net\" WITH KEY = \"instance\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "select": [
      [
       { "params": [ "System_Up_Time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_cpu",
     "query": "SELECT mean(\"Percent_Free_Space\") FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" = 'C:' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Processor_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_mem",
     "select": [
      [
       { "params": [ "Available_Bytes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
     ]
    }
   ]
  },
  {
   "title": "Drive C: Free",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "win_disk",
     "query": "SELECT mean(\"Percent_Free_Space\") FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" = 'C:' AND $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "Percent_Disk_Read_Time" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "instance", "operator": "=", "value": "C:" }
     ]
    }
   ]
  },
  {
   "title": "Disk C: Queue",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT last(\"Current_Disk_Queue_Length\") FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"objectname\" = 'LogicalDisk'  AND \"instance\" = 'C:' AND $timeFilter GROUP BY time(10s) fill(null)",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Processing State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT (\"processingstate\") FROM \"processingstats\"",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Log Updating",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "processingstats",
     "query": "SELECT (\"logwritestate\") FROM \"processingstats\"",
     "select": [
      [
       { "params": [ "logwritestate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "SQL Agent State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT (\"sqlagentstate\") FROM \"processingstats\"",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "SQL Service State",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT (\"sqlserverstate\") FROM \"processingstats\"",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "SQL EOD Query",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT (\"value\") FROM \"sqlquery\"",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  {
   "title": "Last Log Write ",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "measurement": "win_system",
     "query": "SELECT (\"value\") FROM \"logwrite\"",
     "select": [
      [
       { "params": [ "Threads" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "objectname", "operator": "=", "value": "System" }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "measurement": "app_log",
     "select": [
      [
       { "params": [ "logmessage" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 5, "x": 12, "y": 6 } },
  {
   "title": "Alert Panel",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Processing State",
     "measurement": "processingstats",
     "select": [
      [
       { "params": [ "processingstate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "LogWrite State",
     "measurement": "processingstats",
     "select": [
      [
       { "params": [ "logwritestate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SQL Agent State",
     "measurement": "processingstats",
     "select": [
      [
       { "params": [ "sqlagentstate" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "SQL Server State",
     "measurement": "processingstats",
     "select": [
      [
       { "params": [ "sqlserverstate" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "auto" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_cpu",
       "select": [
        [
         { "params": [ "Percent_Privileged_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Priviledged Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_User_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% User Time" ], "type": "alias" }
        ],
        [
         { "params": [ "Percent_Interrupt_Time" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ "% Interrupt Time" ], "type": "alias" }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Available_Bytes\") as \"Available Bytes\", mean(\"Pool_Nonpaged_Bytes\") as \"Pool Nonpaged Bytes\", mean(\"Pool_Paged_Bytes\") as \"Pool Paged Bytes\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Memory Usage Rates",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Cache_Faults_persec\") as \"Cache Faults persec\", mean(\"Demand_Zero_Faults_persec\") as \"Demand Zero Faults persec\", mean(\"Page_Faults_persec\") as \"Page Faults persec\", mean(\"Pages_persec\") as \"Pages persec\", mean(\"Transition_Faults_persec\") as \"Transition Faults persec\" FROM \"win_mem\" WHERE host =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), host fill(linear) ORDER BY asc",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Context Switches",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Context_Switches_persec\") AS \"Context Switches persec\" FROM \"win_system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "System Calls",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_host: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"System_Calls_persec\") AS \"System Calls / sec\" FROM \"win_system\" WHERE \"host\" =~ /$hostname$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "repeat": "disk",
   "collapsed": true,
   "panels": [
    {
     "title": "Disk $disk Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Percent_Free_Space\") AS \"% Free Space\" FROM \"win_disk\" WHERE \"instance\" =~ /^$disk$/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk $disk Usage Split",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Disk_Read_Time\") AS \"% Disk Read Time\", mean(\"Percent_Disk_Write_Time\") AS \"% Disk Write Time\" FROM \"win_disk\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk $disk Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Current_Disk_Queue_Length\") AS \"Current Disk Queue Length\" FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval) fill(0)",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk $disk Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Percent_Free_Space\") AS \"% Free Space\" FROM \"win_disk\" WHERE \"instance\" =~ /^$disk$/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk $disk Usage Split",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Disk_Read_Time\") AS \"% Disk Read Time\", mean(\"Percent_Disk_Write_Time\") AS \"% Disk Write Time\" FROM \"win_disk\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk $disk Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Current_Disk_Queue_Length\") AS \"Current Disk Queue Length\" FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval) fill(0)",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk $disk Free",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Percent_Free_Space\") AS \"% Free Space\" FROM \"win_disk\" WHERE \"instance\" =~ /^$disk$/ AND \"host\" =~ /^$hostname$/ AND $timeFilter GROUP BY time($interval) fill(linear)",
       "select": [
        [
         { "params": [ "Percent_Free_Space" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "instance", "operator": "=~", "value": "/^$disk$/" },
        { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$hostname$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk $disk Usage Split",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Disk_Read_Time\") AS \"% Disk Read Time\", mean(\"Percent_Disk_Write_Time\") AS \"% Disk Write Time\" FROM \"win_disk\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk $disk Queue",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "linear" ], "type": "fill" }
       ],
       "measurement": "win_disk",
       "query": "SELECT mean(\"Current_Disk_Queue_Length\") AS \"Current Disk Queue Length\" FROM \"win_disk\" WHERE \"host\" =~ /^$hostname$/ AND \"instance\" =~ /^$disk$/ AND $timeFilter GROUP BY time($interval) fill(0)",
       "select": [
        [
         { "params": [ "Current_Disk_Queue_Length" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
        { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$disk$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Network Interface $network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "repeat": "network",
   "collapsed": true,
   "panels": [
    {
     "title": "$network Throughput",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Bytes_Received_persec\") AS \"Bytes Received persec\", mean(\"Bytes_Sent_persec\") AS \"Bytes Sent persec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/  AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "$network Packets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $col",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Packets_Received_persec\") AS \"Packets Received / sec\", mean(\"Packets_Sent_persec\") AS \"Packets Sent / sec\" FROM \"win_net\" WHERE \"host\" =~ /$hostname$/ AND \"instance\" =~ /$network$/ AND $timeFilter GROUP BY time($interval), \"host\", instance fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "% Processor Time",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$hostname: $tag_instance",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Percent_Processor_Time\") as \"% Processor Time\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND instance =~ /$process$/ AND $timeFilter GROUP BY time($interval), instance fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Handle Count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$hostname: $tag_instance",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Handle_Count\") as \"Handle Count\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND instance =~ /$process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Private Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$hostname: $tag_instance",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Private_Bytes\") as \"Private Bytes\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND instance =~ /$process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Virtual Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$hostname: $tag_instance",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Virtual_Bytes\") as \"Virtual Bytes\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND instance =~ /$process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Working Set",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$hostname: $tag_instance",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"Working_Set\") as \"Working Set\" FROM \"win_proc\" WHERE host =~ /$hostname$/ AND instance =~ /$process$/ AND $timeFilter GROUP BY time($interval), instance fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}